### ISSUE TITLE
Verkabelung falsch herum?

### ISSUE THREAD

**Issue by baba2k** [micw/ir-lesekopf#1]
Hallo @micw,

muss nicht, anders als in der Doku unter Verkabelung beschrieben, RX vom Lesekopf an TX vom Schreibkopf und dann TX vom Schreibkopf an RX von USB-TTL/ESP?

LG baba

**Comment by micw** [comment]
Danke für den Hinweis. Im langen Text steht es korrekt, in der Zusammenfassung falsch
> TX vom Lesekopf wird an RX des Schreibkopfes und an einem GPIO des ESP angeschlossen.

muss heißen

> RX vom Lesekopf wird an TX des Schreibkopfes und an einem GPIO des ESP angeschlossen.

**Comment by micw** [comment]
Nochmal Update, oben bezieht sich auf was anders. Ist also die einzige Stelle, wo es steht und dort ist es falsch.

**Comment by baba2k** [comment]
Danke, dann löte ich das mal um 😀

**Comment by micw** [comment]
Sorry für die Umstände...
